server:
  port: 8000

eureka:
  client:
    serviceUrl:
      #defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true # 优先注册IP地址而不是hostname
  healthcheck:
      enabled: true # 启用健康检查,注意:需要引用spring boot actuator

spring:
  application:
    name: user-service
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/world?characterEncodingncoding=UTF-8&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&noAccessToProcedureBodies=true
    username: root
    password: 123456
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true
  logging:
    level:
      root: INFO
      org.hibernate: INFO
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@